### ISSUE TITLE
What's the license for the code in this repo?

### ISSUE THREAD

**Issue by m90** [balena-io-playground/balena-engine-docker#2]
I'd like to use the files in this repo in a project of mine where I run tests targeting Docker Engine against alternative options like Balena. Before I start copying things over I'd need to know about the conditions under which I am allowed to do so though.

Would you be able to provide a license along with the files?

**Comment by klutchell** [comment]
Hey @m90 , the license for all balena projects in this org is Apache License v2.0 and I've added a LICENSE file to this repo!

**Comment by m90** [comment]
Brilliant, thank you very much!
